services:
  - type: web
    name: expense-tracker
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn expense_tracker.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expense_db
          property: connectionString
      - key: SECRET_KEY
        value: your-strong-secret-key
