services:
  - type: web
    name: expense-tracker-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./entrypoint.sh
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
